# http://travis-ci.org/#!/jaraco/keyring
#

sudo: required

matrix:
    include:
        - language: generic
          os: osx
          osx_image: beta-xcode6.3

script:
  - curl https://bootstrap.pypa.io/get-pip.py -o - | sudo python
  - sudo pip install -U setuptools
  - python setup.py test --addopts="-rs -v"
