# http://travis-ci.org/#!/jaraco/keyring
#

sudo: required

matrix:
    include:
        - language: generic
          os: osx
          osx_image: beta-xcode6.3

script:
  - sudo easy_install -U virtualenv
  - virtualenv ~/.env
  - ~/.env/bin/pip install -U six
  - ~/.env/bin/python setup.py test --addopts="-rs -v"
