# http://travis-ci.org/#!/jaraco/keyring
#

sudo: required

matrix:
    include:
        - language: generic
          os: osx
          osx_image: beta-xcode6.3

script:
  - pip install -U pytest
  - python setup.py test --addopts="-rs -v"
