# https://travis-ci.org/#!/jaraco/keyring
#

language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic

# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv .env; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .env/bin/activate; fi

script:
  - pip install -U pytest
  - python setup.py test --addopts="-rs -v"
