# http://travis-ci.org/#!/jaraco/keyring
#

matrix:
    include:
        - python: 2.6
        - python: 2.7
        - python: 3.2
        - python: 3.3
        - python: 3.4
        - python: pypy
        - language: generic
          os: osx
          osx_image: beta-xcode6.3

script:
  - python setup.py test --addopts="-rs -v"
